### PR TITLE
Make things shapeless

### PR DESCRIPTION
**Pull request by Apeiros-46B**
Make suspicious stew, endstone, and netherwart block -> netherwart conversion shapeless
**I have not tested this, probably test the changes first before merging**

### CODE REVIEW

**Review by jigglypuff2731 — APPROVED** [review]
sure

**Review by jigglypuff2731 — APPROVED** [review]
yes

**Review by jigglypuff2731 — APPROVED** [review]

**Review by jigglypuff2731 — APPROVED** [review]

**Comment by Apeiros-46B** [comment]
Closing

**Review by jigglypuff2731 — COMMENTED** [review]
e

**Pull request closed without merging**
